name: Docker Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: books-api:latest

      - name: Test API
        run: |
          docker run -d -p 8080:8080 --name test-api books-api
          sleep 5  # Wait for FastAPI to start
          curl http://localhost:8080/books/ | grep "[]"  # Verify empty book list
