name: Docker Build and Test

on:
  push:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: books-api:latest
          platforms: linux/amd64
          load: true

      - name: Test API
        run: |
          docker run -d -p 8080:8080 --name test-api books-api
          sleep 15
          docker logs test-api
          curl -v http://localhost:8080/books/
